import React from "react";
import DetectionForm from "./DetectionForm";
import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <nav>
        <img src={logo} alt="logo" />
        <ul></ul>
      </nav>
      <main>
        <h1>Is this Written by AI?</h1>
        <DetectionForm />

        <footer>
          <h3>About</h3>
          <p>
            Are you concerned that the text you're reading or writing may have
            been generated by an AI model? Look no further than
            isthiswrittenbyai.com! Our website provides a user-friendly and
            reliable way to determine if text was generated by an AI model.
          </p>
          <h3>How Does It Work?</h3>
          <p>
            All you need to do is paste the text you want to analyze into our
            input field and our algorithm will analyze it to determine if it was
            generated by an AI model. Whether you're a student, journalist,
            researcher, or content creator, our tool can help ensure the
            authenticity of your work.
          </p>
          <h3>Limitations</h3>
          <p>
            Please note that this service has its limitations. Although our
            algorithm is highly accurate, there is always a chance that
            human-generated text can be mistakenly classified as AI-generated,
            and vice versa. Additionally, our service is limited to detecting
            text generated by certain AI models and may not be able to detect
            text generated by other AI models.
            <br />
            Despite these limitations, isthiswrittenbyai.com provides a
            convinient wzay for anyone to analyze the authenticity of their
            content.
          </p>
        </footer>
      </main>
    </div>
  );
}

export default App;
