import React from "react";
import DetectionForm from "./DetectionForm";
import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <nav>
        <img src={logo} alt="logo" />
        <ul></ul>
      </nav>
      <main>
        <h1>Is This Written By ChatGPT?</h1>
        <DetectionForm />

        <footer>
          <h3>About</h3>
          <p>
            Have you ever wondered if a piece of text was written by a language
            model like ChatGPT? Check it out on isthiswrittenbychatgpt.com! Our
            website provides a quick and easy way to detect if text was
            generated by a language model.
          </p>
          <h3>How to Use It?</h3>
          <p>
            Simply paste the text in question into our input field and our
            algorithm will analyze it to determine if it was generated by a
            language model like ChatGPT. Our tool is useful for writers,
            researchers, academics, and anyone who wants to ensure the
            authenticity of their writing.
          </p>
          <h3>Limitations</h3>
          <p>
            Although our algorithm is highly accurate, there is always a chance
            that human-generated text can be mistakenly classified as
            model-generated, and vice versa. Additionally, our service is
            limited to detecting text generated by certain language models and
            may not be able to detect text generated by other models.
          </p>
        </footer>
      </main>
    </div>
  );
}

export default App;
