import React from "react";
import DetectionForm from "./DetectionForm";
import logo from "./logo.svg";
import "./App.css";

function App() {
  return (
    <div className="App">
      <nav>
        <img src={logo} alt="logo" />
        <ul></ul>
      </nav>
      <main>
        <h1>Is this GPT Written?</h1>
        <DetectionForm />

        <footer>
          <h3>About</h3>
          <p>
            Are you unsure if a piece of text was written by an AI model like
            GPT? Look no further than gptwritten.com! Our website provides a
            quick and easy way to detect if text was generated by an AI model.
          </p>
          <h3>How to Use It?</h3>
          <p>
            Simply input the text in question and our algorithm will analyze it
            to determine if it was generated by an AI model. This can be
            particularly useful for writers, researchers, academics, and
            journalists who want to ensure that their work is original and not
            inadvertently plagiarized from an AI-generated source.{" "}
          </p>
          <h3>Limitations</h3>
          <p>
            However, please note that there are limitations to our service.
            While our algorithm is highly accurate, there is always a chance
            that human-generated text can be mistakenly classified as
            AI-generated, and vice versa. Additionally, our service only detects
            text generated by GPT models specifically, and may not be able to
            detect text generated by other AI models.
            <br />
            Despite these limitations, gptwritten.com provides a valuable tool
            for anyone who wants to ensure that their writing is authentic and
            original. So why wait? Try our detection form today and put your
            mind at ease!
          </p>
        </footer>
      </main>
    </div>
  );
}

export default App;
